version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    environment:
      - POSTGRES_USER=Htubyf
      - POSTGRES_PASSWORD=4221
      - POSTGRES_DB=scrapper
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  liquibase-migrations:
    container_name: liquibase
    image: liquibase/liquibase:4.18
    restart: on-failure
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=Htubyf
      - --password=4221
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    ports:
       - "5672:5672"
       - "15672:15672"
    volumes:
       - ./rabbitmq_data:/var/lib/rabbitmq
networks:
  backend:
    driver: bridge